---
spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:file:./data/database
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      generate-ddl: true
      ddl-auto: update 
  h2:
    console:
      enabled: true